=== DrParadox7/Lost-Era-Modpack/config/WarpDrive/WarpDrive.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
	version="1.0"
	elementFormDefault="qualified"
	targetNamespace="http://warpdrive.lemadec.org"
	xmlns:wd="http://warpdrive.lemadec.org"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:complexType name="elementFor">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="for" type="wd:elementFor" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="import" type="wd:elementImport" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="filler" type="wd:elementFiller" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="metashell" type="wd:elementMetashell" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="replacement" type="wd:elementReplacement" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="shell" type="wd:elementShell" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
		<xs:attribute name="variable" type="xs:string" use="required" />
		<xs:attribute name="from" type="xs:string" use="optional" />
		<xs:attribute name="to" type="xs:string" use="optional" />
		<xs:attribute name="in" type="xs:string" use="optional" />
		<xs:attribute name="mods" type="xs:string" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="elementFillerSet">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="for" type="wd:elementFor" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="import" type="wd:elementImport" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="filler" type="wd:elementFiller" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
		<xs:attribute name="group" type="xs:string" use="required" />
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="weight" type="xs:string" use="optional" />
		<xs:attribute name="ratio" type="xs:string" use="optional" />
		<xs:attribute name="mods" type="xs:string" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="elementImport">
		<xs:attribute name="group" type="xs:string" use="required" />
		<xs:attribute name="name" type="xs:string" use="optional" />
		<xs:attribute name="mods" type="xs:string" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="elementFiller">
		<xs:attribute name="block" type="xs:string" use="required" />
		<xs:attribute name="metadata" type="xs:string" use="optional" />
		<xs:attribute name="nbt" type="xs:string" use="optional" />
		<xs:attribute name="weight" type="xs:string" use="optional" />
		<xs:attribute name="ratio" type="xs:string" use="optional" />
		<xs:attribute name="mods" type="xs:string" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="elementStructure">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="for" type="wd:elementFor" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="import" type="wd:elementImport" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="metashell" type="wd:elementMetashell" minOccurs="0" maxOccurs="1" />
			<xs:element name="schematic" type="wd:elementSchematic" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="shell" type="wd:elementShell" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
		<xs:attribute name="group" type="xs:string" use="required" />
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="weight" type="xs:string" use="optional" />
		<xs:attribute name="ratio" type="xs:string" use="optional" />
		<xs:attribute name="mods" type="xs:string" use="optional" />
	</xs:complexType>
	
    <xs:complexType name="elementSchematic">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="for" type="wd:elementFor" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="replacement" type="wd:elementReplacement" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
        <xs:attribute name="group" type="xs:string" use="required" />
        <xs:attribute name="name" type="xs:string" use="optional" />
		<xs:attribute name="filename" type="xs:string" use="required" />
		<xs:attribute name="weight" type="xs:string" use="optional" />
		<xs:attribute name="ratio" type="xs:string" use="optional" />
        <xs:attribute name="mods" type="xs:string" use="optional" />
    </xs:complexType>
	
	<xs:complexType name="elementReplacement">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="for" type="wd:elementFor" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="import" type="wd:elementImport" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="filler" type="wd:elementFiller" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
		<xs:attribute name="block" type="xs:string" use="required" />
		<xs:attribute name="metadata" type="xs:string" use="optional" />
		<xs:attribute name="mods" type="xs:string" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="elementLootSet">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="for" type="wd:elementFor" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="loot" type="wd:elementLoot" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
		<xs:attribute name="group" type="xs:string" use="required" />
		<xs:attribute name="name" type="xs:string" use="optional" />
		<xs:attribute name="weight" type="xs:string" use="optional" />
		<xs:attribute name="ratio" type="xs:string" use="optional" />
		<xs:attribute name="mods" type="xs:string" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="elementLoot">
		<xs:attribute name="item" type="xs:string" use="required" />
		<xs:attribute name="damage" type="xs:string" use="optional" />
		<xs:attribute name="nbt" type="xs:string" use="optional" />
		<xs:attribute name="minQuantity" type="xs:string" use="optional" />
		<xs:attribute name="maxQuantity" type="xs:string" use="optional" />
		<xs:attribute name="weight" type="xs:string" use="optional" />
		<xs:attribute name="ratio" type="xs:string" use="optional" />
		<xs:attribute name="mods" type="xs:string" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="elementMetashell">
		<xs:attribute name="block" type="xs:string" use="optional" />
		<xs:attribute name="metadata" type="xs:string" use="optional" />
		<xs:attribute name="minCount" type="xs:string" use="required" />
		<xs:attribute name="maxCount" type="xs:string" use="required" />
		<xs:attribute name="minRadius" type="xs:string" use="required" />
		<xs:attribute name="relativeRadius" type="xs:string" use="required" />
		<xs:attribute name="mods" type="xs:string" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="elementShell">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="for" type="wd:elementFor" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="import" type="wd:elementImport" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="filler" type="wd:elementFiller" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="minThickness" type="xs:string" use="required" />
		<xs:attribute name="maxThickness" type="xs:string" use="required" />
		<xs:attribute name="mods" type="xs:string" use="optional" />
	</xs:complexType>
	
	
	<xs:complexType name="elementCelestialObject">
		<xs:sequence>
			<xs:element name="parent" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:annotation>
						<xs:documentation xml:lang="en">
							Coordinates in parent celestial object
							Optional: when not defined, current celestial object is an hyperspace dimension.
						</xs:documentation>
					</xs:annotation>
					<xs:sequence>
						<xs:element name="center" type="wd:elementPosition" minOccurs="1" maxOccurs="1" />
					</xs:sequence>
					<xs:attribute name="id" type="xs:string" use="optional" />
				</xs:complexType>
			</xs:element>
			
			<xs:element name="size" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:attribute name="x" type="wd:typeWorldSize" use="required" />
					<xs:attribute name="z" type="wd:typeWorldSize" use="required" />
				</xs:complexType>
			</xs:element>
			
			<xs:element name="name" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1" />
			
			<xs:element name="nbt" type="xs:string" minOccurs="0" maxOccurs="1" />
			
			<xs:element name="dimension" type="wd:elementDimension" minOccurs="0" maxOccurs="1" />
			
			<xs:element name="skybox" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:annotation>
						<xs:documentation xml:lang="en">
							Sky rendering parameters
						</xs:documentation>
					</xs:annotation>
					<xs:sequence>
						<xs:element name="backgroundColor" type="wd:elementColor" minOccurs="0" maxOccurs="1" />
						<xs:element name="starBrightnessBase" type="xs:float" minOccurs="0" maxOccurs="1" />
						<xs:element name="starBrightnessVanilla" type="xs:float" minOccurs="0" maxOccurs="1" />
						<xs:element name="celestialObjectOpacity" type="xs:float" minOccurs="0" maxOccurs="1" />
						<xs:element name="fogColor" type="wd:elementColor" minOccurs="0" maxOccurs="1" />
						<xs:element name="fogFactor" type="wd:elementColor" minOccurs="0" maxOccurs="1" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="render" type="wd:elementRender" minOccurs="0" maxOccurs="unbounded" />
			
			<xs:choice minOccurs="0" maxOccurs="1">
				<xs:element name="for" type="wd:elementFor" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="celestialObject" type="wd:elementCelestialObject" minOccurs="0" maxOccurs="unbounded" />
			</xs:choice>
		</xs:sequence>
		
		<xs:attribute name="id" type="xs:string" use="required" />
		<xs:attribute name="mods" type="xs:string" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="elementDimension">
		<xs:annotation>
			<xs:documentation xml:lang="en">
				Defines the actual game world characteristics.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence minOccurs="1" maxOccurs="1">
			<xs:element name="center" type="wd:elementPosition" minOccurs="1" maxOccurs="1" />
			<xs:element name="provider" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:union memberTypes="xs:double">
								<xs:simpleType>
									<xs:restriction base="xs:NMTOKEN">
										<xs:enumeration value="auto" />
										<xs:enumeration value="WarpDriveSpace" />
										<xs:enumeration value="WarpDriveHyperspace" />
										<xs:enumeration value="other" />
									</xs:restriction>
								</xs:simpleType>
							</xs:union>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="generate" type="wd:elementGenerate" minOccurs="0" maxOccurs="unbounded" />
			<!-- <xs:element name="effects" type="wd:effectElement" minOccurs="0" maxOccurs="unbounded" /> @TODO Not implemented -->
		</xs:sequence>
		
		<xs:attribute name="id" type="xs:int" use="required" />		
		<xs:attribute name="isBreathable" type="xs:boolean" use="required" />
		<xs:attribute name="isHyperspace" type="xs:boolean" use="optional" default="false" />
		<xs:attribute name="gravity" use="required">
			<xs:simpleType>
				<xs:union memberTypes="xs:double">
					<xs:simpleType>
						<xs:restriction base="xs:NMTOKEN">
							<xs:enumeration value="none" />
							<xs:enumeration value="legacySpace" />
							<xs:enumeration value="legacyHyperspace" />
							<xs:enumeration value="normal" />
						</xs:restriction>
					</xs:simpleType>
				</xs:union>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="mods" type="xs:string" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="elementPosition">
		<xs:attribute name="x" type="wd:typeWorldPosition" use="required" />
		<xs:attribute name="z" type="wd:typeWorldPosition" use="required" />
	</xs:complexType>
	
	<xs:complexType name="elementColor">
		<xs:attribute name="red" type="xs:float" use="required" />
		<xs:attribute name="green" type="xs:float" use="required" />
		<xs:attribute name="blue" type="xs:float" use="required" />
	</xs:complexType>
	
	<xs:complexType name="elementRender">
		<xs:attribute name="red" type="xs:float" use="required" />
		<xs:attribute name="green" type="xs:float" use="required" />
		<xs:attribute name="blue" type="xs:float" use="required" />
		<xs:attribute name="alpha" type="xs:float" use="required" />
		<xs:attribute name="texture" type="xs:string" use="optional" />
		<xs:attribute name="periodU" type="xs:double" use="optional" default="0.0" />
		<xs:attribute name="periodV" type="xs:double" use="optional" default="0.0" />
		<xs:attribute name="additive" type="xs:boolean" use="optional" default="false" />
	</xs:complexType>
	
	<xs:complexType name="elementGenerate">
		<xs:attribute name="group" type="xs:string" use="required" />
		<xs:attribute name="ratio" type="xs:string" use="required" />
	</xs:complexType>
	
	
	<xs:simpleType name="typeWorldSize">
		<xs:restriction base="xs:unsignedInt">
			<xs:maxInclusive value="60000000" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="typeWorldPosition">
		<xs:annotation>
			<xs:documentation xml:lang="en">
				Vanilla block positions is limited to +/- 30000 km.
				Vanilla entities positions are computed on simple float precision, which is 6 digits precision => 1000 km.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:int">
			<xs:minInclusive value="-1000000" />
			<xs:maxInclusive value="1000000" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="elementForRoot">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="for" type="wd:elementForRoot" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="fillerSet" type="wd:elementFillerSet" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="lootSet" type="wd:elementLootSet" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="schematic" type="wd:elementSchematic" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="structure" type="wd:elementStructure" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="celestialObject" type="wd:elementCelestialObject" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
		<xs:attribute name="variable" type="xs:string" use="required" />
		<xs:attribute name="from" type="xs:string" use="optional" />
		<xs:attribute name="to" type="xs:string" use="optional" />
		<xs:attribute name="in" type="xs:string" use="optional" />
		<xs:attribute name="mods" type="xs:string" use="optional" />
	</xs:complexType>
	
	<xs:element name="worldGeneration">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="for" type="wd:elementForRoot" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="fillerSet" type="wd:elementFillerSet" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="lootSet" type="wd:elementLootSet" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="schematic" type="wd:elementSchematic" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="structure" type="wd:elementStructure" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="celestialObject" type="wd:elementCelestialObject" minOccurs="0" maxOccurs="unbounded" />
			</xs:choice>
			<xs:attribute name="version" type="xs:string" use="required" fixed="2" />
			<xs:attribute name="mods" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== DrParadox7/Lost-Era-Modpack/config/WarpDrive/celestialObjects-default.xml
<?xml version="1.0" encoding="utf-8"?>
<worldGeneration version="2"
				 xmlns="http://warpdrive.lemadec.org"
				 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				 xsi:schemaLocation="http://warpdrive.lemadec.org WarpDrive.xsd">
	
	<!--
	  An astronomical object or celestial object is a naturally occurring physical entity, association, or structure in the observable universe.
	  They can be a planet, a more abstract construct like solar system (space dimension) or the all mighty hyperspace.
	  Hyperspace is defined by its WarpDriveHyperspace dimension provider.
	  Space is a dimension with Hyperspace as its parent.
	  
	  This default configuration is fairly simple.
	  In practice, you can have several hyperspaces containing multiple spaces containing numerous planets, etc..
	  
	  When no dimension is defined, a celestial object is considered 'virtual'. An hyperspace can be virtual. A sun is (in most cases) virtual.
	  In theory, multiple planets can exists in the same Minecraft world (for example: The Twilight Forest exist on multiple planets in different star systems).
	  
	  celestialObject.id should be unique for each Celestial object.
	  When provided by WarpDrive, this is the world folder name instead of DIMxxx.
	  -->
	
	
	<!-- Top level is hyperspace, typically a galaxy. -->
	<celestialObject id="Hyperspace">
		<!--
		  size defines the world border size, measured in blocks. This is also the size of the orbit area in space, so don't go too big.
		  name defines an optional display name for the player HUD. It defaults to the celestialObject's id. 
		  description defines an optional text displayed on the player HUD.
		  name and description support colors with § or & as the escape code. '\n' is also supported.
		  nbt defines a JSON string for custom tags. It's used by WarpDrive extensions.
		  -->
		<size x="59999999" z="59999999" />
		<name>Hyperspace</name>
		<description>Your ship warp bubble is your\nonly protection.</description>
		
		<!--
		  dimension defines an actual game world. If it's missing, that celestialObject remains visible but you can't "land" on it.  
		  dimension.id: this is the id of the dimension. 0 is the Overworld, -1 is the Nether, 1 is the End.
		  dimension.isBreathable: this is a boolean flag defining if ambient atmosphere is breathable.
		  dimension.isHyperspace: this is a boolean flag defining if this an hyperspace dimension. 
		  dimension.gravity: this is the gravity simulation type. Valid keywords are 'none' (0.0), 'legacySpace', 'legacyHyperspace', 'normal' (1.0) or any value between 0 and 1.
		  dimension.center.x, dimension.center.z: those are the center coordinate of that dimension world border, measured in blocks. For convenience, it's usually 0, 0.
		  -->
		<dimension id="-3" isBreathable="false" isHyperspace="true" gravity="legacyHyperspace">
			<center x="0" z="0" />
			<!--
			  provider defines how the world biomes are generated. If it's missing, the mod tries to self-assign space and hyperspace dimensions.
			  provider.type: this is the provider type. Valid keywords are "auto", "WarpDriveSpace", "WarpDriveHyperspace", "other".
			  Currently only Space and Hyperspace can be provided: use other mods to generate planet world.
			  -->
			<provider type="WarpDriveHyperspace" />
		</dimension>
		
		<!--
		  skybox defines the sky rendering while inside a WarpDrive provided dimensions.
		  Those can be adjusted to your lore: in hyperspace, Babylon 5 is redish, Stargate is bluish, etc.
		  skybox.backgroundColor is self explanatory. Vanilla enforces plain black at max render distance.
		  skybox.starBrightnessBase is the minimum brightness of stars in the sky.
		  skybox.starBrightnessVanilla is how much of the vanilla star brightness is used. Space and hyperspace have no Sun, hence it's a fixed value.
		  skybox.celestialObjectOpacity is used for that eery feeling. 0 will completely hide celestial objects.
		  skybox.fogColor is the main color. Higher values increases the halo effect.
		  skybox.fogFactor is the fog opacity depending on local Sun position. Space and hyperspace have no Sun, hence it's a fixed value.
		  -->
		<skybox>
			<backgroundColor red="1.0" green="0.0" blue="0.0" />
			<starBrightnessBase>0.2</starBrightnessBase>
			<starBrightnessVanilla>0.0</starBrightnessVanilla>
			<celestialObjectOpacity>0.3</celestialObjectOpacity>
			<fogColor red="0.15" green="0.0" blue="0.0" />
			<fogFactor red="0.0" green="0.0" blue="0.0" />
		</skybox>

		<!-- Second level is Outer Space. -->
		<celestialObject id="solarSystem">
			<!--
			  parent defines the relation with a bigger enveloping celestial object.
			  parent.id (optional): when using multiple files, you can attach to a parent by its id.
			  parent.center.x, parent.center.z: this is the center coordinates in the parent dimension, measured in blocks.
			  -->
			<parent>
				<center x="0" z="0" />
			</parent>
			<size x="59999999" z="59999999" />
			<name>Space</name>
			<description>The void, filled with §6resources§r.</description>
			<dimension id="-2" isBreathable="false" gravity="legacySpace">
				<center x="0" z="0" />
				<provider type="WarpDriveSpace" />
				<!--
					generate defines the chance of different structures to generate
					generate.group, generate.name: identify the structure from the related XML files (name is optional)
				  -->
				<generate group="moon" ratio="0.00125" />
				<generate group="asteroid" ratio="0.0067" />
				<generate group="asteroids_field" ratio="0.0016" />
			</dimension>
			
			<skybox>
				<backgroundColor red="0.0" green="0.0" blue="0.0" />
				<starBrightnessBase>0.9</starBrightnessBase>
				<starBrightnessVanilla>0.0</starBrightnessVanilla>
				<celestialObjectOpacity>1.0</celestialObjectOpacity>
				<fogColor red="0.0" green="0.0" blue="0.0" />
				<fogFactor red="0.0" green="0.0" blue="0.0" />
			</skybox>
			
			<!-- Earth is the overworld (dimension.id is 0) -->
			<celestialObject id="earth">
				<parent>
					<!-- coordinates in the solar system, measured in blocks -->
					<center x="0" z="0" />
				</parent>
				<size x="59999999" z="59999999" />
				<dimension id="0" isBreathable="true" gravity="normal">
					<center x="0" z="0" />
				</dimension>
				<render red="0.70" green="0.70" blue="0.70" alpha="1.00" texture="warpdrive:textures/celestial/surface_temperate2.png" />
				<render red="0.90" green="0.95" blue="1.00" alpha="0.15" texture="warpdrive:textures/celestial/cloud_small1.png" periodU="100" periodV="1100" additive="true" />
				<render red="0.90" green="0.90" blue="1.00" alpha="0.15" texture="warpdrive:textures/celestial/cloud_medium1.png" periodU="300" periodV="1500" additive="false" />
				<render red="0.80" green="0.70" blue="1.00" alpha="0.15" texture="warpdrive:textures/celestial/cloud_large1.png" periodU="500" periodV="2100" additive="false" />
				<render red="0.50" green="0.50" blue="1.00" alpha="0.08" />
				<render red="0.50" green="0.50" blue="1.00" alpha="0.08" />
				<render red="0.50" green="0.50" blue="1.00" alpha="0.08" />
			</celestialObject>

		</celestialObject>

	</celestialObject>
	
</worldGeneration>
